### PR TITLE
feat: randomize palette

### PR DESCRIPTION
**Pull request by ndom91**
Added a colors API to randomize the palette upon button press. Also moved around the design a bit to always show the code section to the left. Hope ya like it!

I also added a little function I reverse engineered out of `coolors.co` (all credit to them!), to log out the color palette and its hex codes in nice little blocks in the console:

image

Example deploy: https://whatamesh-zeta.vercel.app/

### CODE REVIEW

**Comment by ndom91** [comment]
Okay so for some reason its not refreshing the random palette correctly while the dev tools are closed :thinking: 

Working on this..

**EDIT**: Found a more reliable color API. Should be working just fine now :grin:

Nevermind, its not available via HTTPS so insecure-content blocks it in prod (on vercel) :facepalm: 

**EDIT 2**: You'd be surprised how hard it is to find a reliable random color palette generating API haha. Ended up just using an npm package [`color-schemes-generator`](https://npm.im/color-schemes-generator). Seems to be working as planned finally!

**Comment by jordienr** [comment]
Hello! Thanks for your work I really appreciate it. 

If you can make it responsive again I'll merge your code. It may seem weird since the tool is for generating code but I believe it makes it more "shareable" since people can try it on their phone if they're not in their laptop.

**Comment by ndom91** [comment]
@jordienr Alright awesome, sorry for the delayed response! Its now responsive again :grin:

**Comment by ndom91** [comment]
Also changed the page title from `Vite app` to `whatamesh` and added an example mesh as the favicon :tada: 


image

**Comment by ndom91** [comment]
Hope you don't mind - I also cleaned up and fixed your "Play / Pause" and "Darken Top" buttons / functionality. Those are now enabled as well. Feel free to comment those buttons back out though if you explicitly didn't want that functionality in here at the moment.. :+1:

**Review by jordienr — APPROVED** [review]

**Comment by jordienr** [comment]
Merged! Thanks for your contribution :)

**Pull request merged**
